### ISSUE TITLE
Not working in Mint 17.1 

### ISSUE THREAD

**Issue by vveliev** [projecthamster/cinnamon-applet#14]
info t=2014-12-03T02:08:39.707Z Adding systray: mintupdate.py
error t=2014-12-03T02:09:07.834Z No JS module 'dbus' found in search path
trace t=2014-12-03T02:09:07.834Z 
<----------------
@/home/vagif/.local/share/cinnamon/applets/hamster@projecthamster.wordpress.com/applet.js:22
Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:152
Extension@/usr/share/cinnamon/js/ui/extension.js:119
loadExtension@/usr/share/cinnamon/js/ui/extension.js:383
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:192
---------------->
error t=2014-12-03T02:09:07.834Z [Applet "hamster@projecthamster.wordpress.com"]: Error importing applet.js from hamster@projecthamster.wordpress.com
error t=2014-12-03T02:09:07.835Z Could not load applet hamster@projecthamster.wordpress.com

**Comment by danielesegato** [comment]
I can confirm @jimmypoms fix works for me on Rebecca (17.1)

**Comment by SvenRieke** [comment]
I also tried https://github.com/projecthamster/cinnamon-applet/pull/15 and it works fine.

**Comment by sackwort** [comment]
I can't get this to work in Mint 17.1. I've cloned the git repository into ~/.local/share/cinnamon/applets, and installed Time Tracker 1.04.

When I try to add the applet to the panel I get the same error as vveliev.

**Comment by jimmypoms** [comment]
Some thoughts on that:
- do you have the up-to-date version (try "git pull origin master" inside the "~/.local/share/cinnamon/applets/hamster@projecthamster.wordpress.com" folder)
- do you have an older version installed in /usr/share/cinnamon/applets (I'm not sure about precedences for applet loading, but this might interfere with your local applet)
- did you try turning it off and on again ;)

**Comment by sackwort** [comment]
Thanks for your response, @jimmypoms.

I did: git clone https://github.com/projecthamster/cinnamon-applet.git ~/.local/share/cinnamon/applets/hamster@projecthamster.wordpress.com. That should be the latest version, shouldn't it?

This is a clean Mint install that I did this today; I don't have an older version of the applet installed.

I did try turning it on and off within the add applets to panels dialogue.

**Comment by jimmypoms** [comment]
hmm that truly is a bit weird. You are right, it should be the latest version, however there is no dbus import in the latest version anymore :/. 

Could you still perform a `git pull origin master` and a `git checkout master` inside ~/.local/share/cinnamon/applets/hamster@projecthamster.wordpress.com. You never know :)

Could you post the Looking Glass output. The thing is, if you are on the newest version, it can't be the same error as the one described by vveliev.

**Comment by sackwort** [comment]
I'm sorry to be a pain, but I'm very new to git and I can't work out what I need to do to follow your git pull instructions. Would you mind giving me a pointer?

**Comment by jimmypoms** [comment]
don't worry about it :) just paste the following commands into your terminal. try adding and removing the applet from the panel afterwards.

```
cd ~/.local/share/cinnamon/applets/hamster@projecthamster.wordpress.com
git checkout master
git pull origin master
```

If this did not work follow these steps:
- right click the panel -> Troubleshoot ... -> Looking Glass
- an overlay will apear (you can exit with ESC key)
- switch to the log tab
- remove and add the hamster applet
- there should be some errors displayed in the log
- if you could post the errors there's more exact info on what's the problem :)

**Comment by sackwort** [comment]
I followed your git instructions, and it reported "Already up-to-date", but I tried adding the applet again and it worked this time. I don't know why, though! The only thing I did differently this time was that I already had Time Tracker running when I added the applet.

Sorry if I've wasted your time. Thanks very much for your help.

**Comment by jimmypoms** [comment]
no problem ... glad it worked out

**Comment by vveliev** [comment]
thanks for help. 
after updating applet from git everything is working.

**Comment by dagaz** [comment]
Also a big thank you from me. Updadating from Git also works for me.
(Arch Linux, Cinnamon 2.8.6)

It would be nice if the new version would be on the Cinnamon applet page.

**Comment by anurupr** [comment]
same as @dagaz  [ Linux mint 17.3 ( Rosa ) , Cinnamon 2.8.6 ] . If they update the version on the Cinnamon applet , things should be fine
