### ISSUE TITLE
No JS module 'dbus' found in search path

### ISSUE THREAD

**Issue by ManuelSchneid3r** [projecthamster/cinnamon-applet#17]
https://github.com/linuxmint/Cinnamon/issues/4121#issuecomment-99539352

I mean I saw a fix somewhere. Please push upstream.

**Comment by Songworks** [comment]
Came upon the same problem after updating to Linux Mint Cinnamon 17.1.
However, the latest master of this repository already contains the necessary fixes to the dbus stuff.
So in that regard it works again for me.

**Comment by border0464111** [comment]
Applet have been updated on cinnamon spice 
https://github.com/linuxmint/cinnamon-spices-applets/commit/bcd6d7e1987354ae2d981b5f232fee693c675a16

It should solve the issue

**Comment by elbenfreund** [comment]
As this [Issue](https://github.com/projecthamster/cinnamon-applet/issues/30) documents the cinnamon applet is now maintained by the Mint Linux team.
As such this repository is kept around for historical and migration reasons.
Contributors are encouraged to head over there and no work will be done on this
repository at all.
Thanks for your support.
