### ISSUE TITLE
Questionable licensing

### ISSUE THREAD

**Issue by rapgro** [projecthamster/cinnamon-applet#21]
https://github.com/projecthamster/cinnamon-applet/blob/b251b05f76d8e2c17f267900abfcfdae4cdd78c2/applet.js#L10
>  * Portions originate from the gnome-shell source code, Copyright (c)
>  * its respectives authors.
>  * This project is released under the GNU GPL License.
>  * See COPYING for details.

Please provide a valid COPYING file. Can you add this header to all javascript files (also prefs.js and stuff.js)?

**Comment by elbenfreund** [comment]
This is important, thank you for pointing it out. Does anyone feel like providing the relevant changes as a PR? :)

**Comment by elbenfreund** [comment]
@orschiro could you please have a look at this?

**Comment by orschiro** [comment]
@elbenfreund please see the pull requests. 

Warmly,

~Robert

**Comment by elbenfreund** [comment]
Thank you @orschiro . Could you warp this up in one PR with one commit please?

**Comment by orschiro** [comment]
I will see what I can do. Do you know if I can merge them into one using the Github interface or do I have to clone the repository and do the changes to the pull request locally on my machine?

**Comment by elbenfreund** [comment]
I am 100% sure but I do not think you can do this via the github interface.
If you need help with the process, let us know.

**Comment by orschiro** [comment]
I might have found a solution that I will try!

https://webapps.stackexchange.com/questions/95940/how-can-i-change-multiple-files-and-submit-them-in-one-pull-request-on-github/95961#95961

**Comment by orschiro** [comment]
Now it should be good: https://github.com/projecthamster/cinnamon-applet/pull/27

**Comment by elbenfreund** [comment]
Closed by: #27
