### ISSUE TITLE
Create a develop branch 

### ISSUE THREAD

**Issue by border0464111** [projecthamster/cinnamon-applet#29]
Projecthamster/cinnamon-applet need a develop branch to push the PR at. But I dont have sufficient permissions to crate it.

**Comment by elbenfreund** [comment]
As this [Issue](https://github.com/projecthamster/cinnamon-applet/issues/30) documents the cinnamon applet is now maintained by the Mint Linux team.
As such this repository is kept around for historical and migration reasons.
Contributors are encouraged to head over there and no work will be done on this
repository at all.
Thanks for your support.
