### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by collinss** [projecthamster/cinnamon-applet#30]
@jonbrett With the Cinnamon applets now being hosted by Linux Mint on Github, we're trying to clean things up and get them working again. It seems like the current version here is more functional than the one we have from the spices site, and I'd like to update your applet to reflect the more recent changes here, if that's OK with you.

I was also wondering what your intentions are for this applet long term. I know you passed off development of the feeds applet. Are you planning to do the same with this one as well, or do you want to maintain it yourself still?

**Comment by jonbrett** [comment]
Hi Stephen,

Thanks for reaching out. I'm happy for someone else to take over
maintenance of this applet too. I will continue to check in from time to
time, but didn't have the time to give to this right now.

Thanks and all the best,
Jon

**Comment by elbenfreund** [comment]
Hello Stephen,

thank you for getting in touch on my behalf as well. Would you be so kind to provide us with a link to the new authoritative mint repository so we can include this in our documentation?

Also you may (or not) be interested that there is ongoing development on the main ``hamster-shell-extension`` that will not only make it play nice with our new codebase but also offers significant improvements to the old (and iirc shared by the cinnamon-applet) code layout - so this may be something that could be of future interest to the mint community.

**Comment by collinss** [comment]
@elbenfreund the applets repository is here: https://github.com/linuxmint/cinnamon-spices-applets
desklets: https://github.com/linuxmint/cinnamon-spices-desklets
extensions: https://github.com/linuxmint/cinnamon-spices-extensions

**Comment by border0464111** [comment]
For references, This is the actual commit : https://github.com/linuxmint/cinnamon-spices-applets/commit/bcd6d7e1987354ae2d981b5f232fee693c675a16 

Big thx to collinss.
